# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: Fab Lab Limerick
description: A space for makers in Limerick city. Coming this April!
author:
  name: Colaborativa.eu
  email: info@colaborativa.eu

future: true

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
    sass_dir: assets/css

# Markdown library
markdown: kramdown
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex

highlighter: true

collections:
  collection_events:
    output: true
  collection_recurrents:
    output: true
  collection_made:
    output: true
  collection_team:
    output: false
  collection_equipment:
    output: true
  collection_homebanner:
    output: false
  collection_how:
    output: true
  collection_news:
    output: true


defaults:
  -
    scope:
      path: ""
      type: collection_events   # <= here you can specify a collection now!
    values:
      layout: single-event
      permalink: /events/:slug/
  -
    scope:
      path: ""
      type: collection_made   # <= here you can specify a collection now!
    values:
      layout: single-made
      permalink: /made/:slug/
  -
    scope:
      path: ""
      type: collection_recurrents   # <= here you can specify a collection now!
    values:
      layout: single-recurrent
      permalink: /recurrents/:slug/
  -
    scope:
      path: ""
      type: collection_how   # <= here you can specify a collection now!
    values:
      layout: how
      permalink: /how/:categories/:slug/
  -
    scope:
      path: ""
      type: collection_news   # <= here you can specify a collection now!
    values:
      layout: how
      permalink: /us/news/:slug/
