# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: Fab Lab Limerick
description: A space for makers in Limerick city. Coming this April!
author:
  name: Colaborativa.eu
  email: info@colaborativa.eu

include: ['.htaccess']

exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - README.md
  - bower.json

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

gems:
  - jekyll-assets
  - jekyll-redirect-from

# Markdown library
markdown: kramdown
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex

highlighter: true

external:
  facebook: https://www.facebook.com/fablablimerick
  twitter: https://twitter.com/fablablimerick
  email: fablab(which is 'at' the)saul.ie
  wiki: https://github.com/FabLabLimerick/fablablimerick.github.io/wiki
  blog: http://fablablimerick.tumblr.com/
  map: "http://www.openstreetmap.org/?mlat=52.66593&mlon=-8.62399#map=18/52.66593/-8.62399"

timetable:
  long_1: "We are open from Monday to Friday, from 9:00 to 17:00."
  long_2: "Late opening evening on Thursdays from 19.30 to 21.30"
  sort: "Open: Monday to Friday, 9:00 to 17:00. Late opening evening on Thursdays 19.30 to 21.30"

collections:
  collection_events:
    output: true
  collection_recurrents:
    output: true
  collection_made:
    output: true
  collection_team:
    output: false
  collection_equipment:
    output: true
  collection_homebanner:
    output: false

defaults:
  -
    scope:
      path: ""
      type: collection_events   # <= here you can specify a collection now!
    values:
      layout: single-event
      permalink: /events/:slug/
  -
    scope:
      path: ""
      type: collection_made   # <= here you can specify a collection now!
    values:
      layout: single-made
      permalink: /made/:slug/
  -
    scope:
      path: ""
      type: collection_recurrents   # <= here you can specify a collection now!
    values:
      layout: single-recurrent
      permalink: /recurrents/:slug/

# Prose configuration
prose:
  rooturl: "app/_posts"
  media: "app/img/events"
  metadata:
    app/_posts/events:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          help: "Introduce a title for the event"
      - name: "layout"
        field:
          element: "hidden"
          value: "single-event"
      - name: "category"
        field:
          element: "hidden"
          value: "events"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: "false"
          help: "Uncheck when writting a draft-event"
      - name: "slug"
        field:
          element: "text"
          label: "File Name or Slug"
          value: "thenewways-gregsaul"
          help: "Introduce the event file name. Lowercase words without accent separated by dash."
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: "/events/thenewways-gregsaul/"
          help: "Introduce the relative link to the event, it has to include file name as indicated."
      - name: "excerpt"
        field:
          element: "text"
          label: "Excerpt"
          help: "A short sentence introducing the event."
      - name: "hours"
        field:
          element: "text"
          label: "Hours"
          value: "25th of March 6pm"
          help: "Date and time of the event celebration in humman readeable format."
      - name: "description"
        field:
          element: "text"
          label: "Description"
          help: "A short paragraph describing the event."
      - name: "fee"
        field:
          element: "text"
          label: "Event Fee"
          value: "Free event"
          help: "Introduce the event fee (for example: Free event or €100 per person)."
      - name: "soon"
        field:
          element: "checkbox"
          label: "Coming soon link"
          value: "false"
          help: "if the event is coming soon (meaning there is not more info page) then select TRUE, otherwise select FALSE."
      - name: "past"
        field:
          element: "checkbox"
          label: "Past Event"
          value: "false"
          help: "Select TRUE or FALSE to indicate a past or future event."
      - name: "imageurl"
        field:
          element: "text"
          label: "Relative link to an image"
          value: "/events/thenewways-gregsaul.jpg"
          help: "Introduce relative link to image. Make sure to load image with same name at /app/img/events/ absolute path using top tool bar."
      - name: "imagedisplay"
        field:
          element: "checkbox"
          label: "Show image caption"
          value: "false"
          help: "Select TRUE or FALSE to show or hide the image caption"
      - name: "imagetitle"
        field:
          element: "text"
          label: "Image caption"
          help: "Introduce a caption for the image"
      - name: "imagecredits"
        field:
          element: "text"
          label: "Image credits"
          help: "Introduce the image credits"
      - name: "imageoriginal"
        field:
          element: "text"
          label: "External Link"
          help: "If exists, then introduce the external link to the original credited image"

assets:
  compress:
    css: false
    js: false

  #

  autowrite: true
  cache: false
  cache_type: filesystem
  cdn:
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  #
  assets:
    - "*.png"
    - "bundle.css"
  #

  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
    - _assets/bower

  #

  features:
    liquid:  false
    integrity: false
    automatic_img_size: false
    automatic_img_alt : true
